# Generated by Django 4.2.1 on 2023-05-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_publicacion_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
